gifs = {
    "help": [
        "BAACAgIAAxkBAAIOe2ZBXhPNd3dZbhXtITsuuZCUQ2_WAAKiUwAC-PUISl_kuW3GIyhpNQQ",
        "BAACAgIAAxkBAAIOgWZBZMCoNGy38BHvMPjk7dRxBuWjAAKuUwAC-PUISgSKwq52n2jSNQQ",
        "BAACAgIAAxkBAAIOjWZBaFzWcJ20OlAQDNCU4mjqwTyTAAK2UwAC-PUISj35y5PI2L9kNQQ",
        "BAACAgIAAxkBAAIOkWZBbD7G65BuxckyHW_NOFt6IjhZAAKUQQAC-PUQSvQ-UV1s5MLcNQQ",
    ]
}
