"""List available files in the conversation.

This tool allows Claude to check what files are available in the current
thread without embedding the file list in the system prompt. This keeps
the system prompt static and cache-friendly.

Replaces the dynamic files_section that was previously in the system prompt.
Moving files info to a tool prevents Anthropic prefix cache invalidation
when files are delivered or uploaded.

NO __init__.py - use direct import:
    from core.tools.list_files import list_files, TOOL_CONFIG
"""

from typing import Any, Dict, List, TYPE_CHECKING

from cache.exec_cache import get_pending_files_for_thread
from core.tools.helpers import format_unified_files_section
from utils.structured_logging import get_logger

if TYPE_CHECKING:
    from aiogram import Bot
    from sqlalchemy.ext.asyncio import AsyncSession

logger = get_logger(__name__)

# Tool definition for Claude API (static — cached with other tools)
LIST_FILES_TOOL = {
    "name":
        "list_files",
    "description":
        "List all files available in the current conversation. "
        "Returns delivered files (images, PDFs, audio, documents sent by user "
        "or generated by you) and pending files (generated but not yet "
        "delivered to user). Call this when the user references attachments, "
        "previously sent files, or generated content. Also call before using "
        "analyze_image, analyze_pdf, transcribe_audio, or deliver_file to "
        "get the correct file_id/temp_id.",
    "input_schema": {
        "type": "object",
        "properties": {},
        "required": []
    },
}


async def list_files(
    bot: 'Bot',  # pylint: disable=unused-argument
    session: 'AsyncSession',
    thread_id: int | None = None,
) -> Dict[str, Any]:
    """List all files available in the conversation thread.

    Queries delivered files from database and pending files from exec_cache,
    then formats them into a structured response.

    Args:
        bot: Telegram Bot instance (unused, for interface consistency).
        session: Database session for querying file metadata.
        thread_id: Thread ID to query files for.

    Returns:
        Dictionary with formatted file listing:
        - If files exist: {"files": "<formatted list>", "delivered": N, "pending": N}
        - If no files: {"files": "none", "message": "No files in this conversation."}
    """
    logger.info("tools.list_files.called", thread_id=thread_id)

    if thread_id is None:
        return {
            "files": "none",
            "message": "No thread context available.",
        }

    try:
        # Query delivered files from DB
        from db.repositories.user_file_repository import UserFileRepository

        user_file_repo = UserFileRepository(session)
        delivered_files: List[Any] = await user_file_repo.get_by_thread_id(
            thread_id)

        # Query pending files from exec_cache (Redis)
        pending_files: List[Dict[str, Any]] = \
            await get_pending_files_for_thread(thread_id)

        if not delivered_files and not pending_files:
            logger.info("tools.list_files.no_files", thread_id=thread_id)
            return {
                "files": "none",
                "message": "No files in this conversation.",
            }

        # Reuse existing formatting function
        formatted = format_unified_files_section(delivered_files,
                                                 pending_files)

        delivered_count = len(delivered_files) if delivered_files else 0
        pending_count = len(pending_files) if pending_files else 0

        logger.info("tools.list_files.success",
                     thread_id=thread_id,
                     delivered=delivered_count,
                     pending=pending_count)

        return {
            "files": formatted,
            "delivered": delivered_count,
            "pending": pending_count,
        }

    except Exception as e:
        logger.info("tools.list_files.error",
                     thread_id=thread_id,
                     error=str(e))
        return {
            "files": "error",
            "message": f"Failed to list files: {str(e)}",
        }


# Unified tool configuration
from core.tools.base import ToolConfig  # pylint: disable=wrong-import-position

TOOL_CONFIG = ToolConfig(
    name="list_files",
    definition=LIST_FILES_TOOL,
    executor=list_files,
    emoji="\U0001f4cb",  # clipboard
    needs_bot_session=True,
)
